### ISSUE TITLE
bounding-convex-decomposition Error: could not load mesh (STL)

### ISSUE THREAD

**Issue by BrettHemes-3M** [gaschler/bounding-mesh#11] opened 2017-02-01 15:05 UTC
I am having trouble getting the convex decomposition to work.  I am able to run `boundingmesh` from the command line successfully as well as the GUI.

In a fresh install of Ubuntu 16.04 I am getting the following error when running `bounding-convex-decomposition`:

> ./bounding-convex-decomposition my_mesh.stl new_mesh.wrl
Loading mesh...
Couldn't load mesh from my_mesh.stl
Error: could not load mesh

**Comment by gaschler** [comment] 2017-02-01 16:23
Thanks for reporting.
This is caused by a missing comparison in FileUtils.cpp.
As a work around, you can use wrl or off or obj as input formats for now.

**Comment by gavanderhoorn** [comment] 2018-04-15 08:45
Is this still an issue?

> This is caused by a missing comparison in FileUtils.cpp.

Could you link to where the comparison is missing?

**Comment by gaschler** [comment] 2018-04-16 08:48
Still an open issue and should be easy to fix: https://github.com/gaschler/bounding-mesh/blob/master/src/boundingmesh/FileUtils.cpp#L63

**Comment by gaschler** [comment] 2018-11-10 11:56
Closing as fixed by #14

**Closed as completed by gaschler** 2018-11-10 11:56 UTC
Labels: bug
